### ISSUE TITLE
Users aren't getting opped

### ISSUE THREAD

**Issue by rwoodpecker** [chfoo/pleaseopme#4]
I'm not able to get the bot to op known users when they join a channel. I speak in the channel, wait 60 seconds, and see in the bot logs that its whoising users but nothing happens when a known users joins a channel.

Running your latest code and willie 5.4.1 on python 3.4.2.

Connecting to irc.servercentral.net:9999...
Connected.
INFO:pleaseopme:Auto join #testbot
INFO:pleaseopme:Grant privilege to channel=#testbot nickname=BOT hostmask@host level=4 
-Wait 60 seconds & part -
-Join channel - not opped by the bot-
-tell the bot to op me works-
INFO:pleaseopme:Op #testbot user
INFO:pleaseopme:Grant privilege to channel=#BOT nickname=user hostmask@host level=4 
-Join & part.. not opped by the bot-

Here's my config:

[pleaseopme]
db_path = /home/willie/.willie/pleaseopme.db
admin_password = password
whitelist =
logging = True
reply_help = True
auto_join = True
auto_part = False
max_channels = False

**Comment by rwoodpecker** [comment]
I just added enable = pleaseopme to my config file and it's started working. I didn't realise this was a requirement? I'm running a brand new install and fresh config files without other modules configured.

**Comment by chfoo** [comment]
Before you added `enable = pleaseopme`, how long did you wait after you joined? The module uses a timer that does 1 op every minute (i.e., not instantaneous). The slow timer was instended as a cheap way of rate-limiting in case many former op users join at once.

I haven't tested it with other modules enabled so it's possible that there might be a conflict with other moduels.

**Comment by rwoodpecker** [comment]
I waited several minutes - up to ten and it still didn't function as expected.

Is there any good method to detect a module conflict?

**Comment by forcecore** [comment]
I think there are two bugs in the code.

Assume there is a bot +o 'ing a known operator.
Also assume that there's someone who uses IRC sript to +v anyone who enters the channel.
Sometimes, +o comes first, earlier than +v.

_priv_tracker.grant()
adds +o to the grant table then immidietly down grants the record to +v.

There is another bug in periodic auto-op, related to above bug.
Assume someone already has the op, but the bot has "v" in the grant table.
Then, auto-op function (auto_priv) tries to "upgrade" the op to "v". (??!!!).
Since the nick-holder is already "o", this one will never become "v",
meaning check_and_change_channel will be stuck at that one forever, since the function returns after "+v" ing the person of interest.

I patched as following and the bot seems to work:

```
diff --git a/pleaseopme.py b/pleaseopme.py
index ec75166..d85535c 100644
--- a/pleaseopme.py
+++ b/pleaseopme.py
@@ -408,6 +408,7 @@ def setup(bot):

     if bot.config.pleaseopme.logging:
         logging.basicConfig(level=logging.INFO)
+        #logging.basicConfig(level=logging.DEBUG)

     _admin_auth = AdminAuth()
     _priv_tracker = PrivilegeTracker(bot.config.pleaseopme.db_path)
@@ -617,6 +618,23 @@ def channel_nick_mode_change(bot, trigger):
             priv_level = STR_TO_PRIV_MAP.get(mode)
             hostmask = _hostmask_map.get(nick.lower())

+            # Since this is not "-" then
+            # if a user gets +v and +o at the same time,
+            # (A user may get +o then +v'ed by different IRC scripts)
+            # I think the maximum level of + should be tracked.
+            if not channel in bot.privileges :
+                continue
+            if not nick in bot.privileges[channel] :
+                continue
+            known_level = bot.privileges[channel][nick]
+
+            _logger.info(
+                    'known_level=%s priv_level=%s', known_level, priv_level
+                )
+
+            priv_level = max( int(priv_level), int(known_level) )
+
             if hostmask and priv_level in PRIVILEGE_LEVELS:
                 _priv_tracker.grant(
                     channel.lower(), nick.lower(), hostmask, priv_level
@@ -741,11 +759,18 @@ def auto_priv(bot):

                 _logger.debug(
                     'Checking channel=%s nick=%s hostmask=%s '
-                    'flags=%s candidate=%s',
+                    'flags=%s candidate=%s level=%s',
                     channel, nick, current_nick_hostmask,
-                    current_nick_priv_flags, mode
+                    current_nick_priv_flags, mode, level
                 )

+                if current_nick_priv_flags > level :
+                    _logger.debug( 'not trying to cast to lower level, duh' )
+                    # Current privilege is larger than in DB.
+                    # Just skip.
+                    continue
+
                 if not current_nick_priv_flags & level and mode \
                         and current_nick_hostmask == tracked_hostmask:
                     _logger.info('Auto mode %s %s %s', channel, nick, mode)
```

**Comment by rwoodpecker** [comment]
Resolved and working - Just wasn't being patient enough, apologies.

Hopefully comment above isn't lost under this.

**Comment by forcecore** [comment]
I think this issue should be re-opened, as it is still affecting me without my modifications.

**Comment by chfoo** [comment]
@forcecore: Are you still having issues as described in the original post or is this about your comment?

**Comment by forcecore** [comment]
Both, I have the issue described by rwoodpecker too, unless I patch as I commented.

**Comment by forcecore** [comment]
This is raw.log:
<<1438148616.4778264    :포도!~yyyy@xx.xx.xx.xx JOIN #chan
<<1438148616.5111816    :^-^EVA!~yyyy@xx.xx.xx.xx MODE #chan +o 포도
<<1438148616.8187363    :Topuxxx!yyyy@xx.xx.xx.xx MODE #chan +v 포도

> > 1438148618.8336856    WHOIS PAntxxxx
> > When someone enters, some IRC bots +o then +v the new user.
> > The user should be an op by now.

This is opme log:
INFO:pleaseopme:Grant privilege to channel=#chan nickname=[s]친절 hostmask=[s]친절!SHEST@xx.xx.xx.xx level=4
INFO:pleaseopme:Grant privilege to channel=#chan nickname=[s]친절 hostmask=[s]친절!SHEST@xx.xx.xx.xx level=1
--- Detected +o and +v commands.

The user is already an op but, tries to +v the user indefinitely.
Calling shutdown for 0 modules.
Closed!
INFO:pleaseopme:Auto mode #chan 포도 v
Calling shutdown for 0 modules.
Closed!
INFO:pleaseopme:Auto mode #chan 포도 v
Calling shutdown for 0 modules.
Closed!
INFO:pleaseopme:Auto mode #chan 포도 v
Calling shutdown for 0 modules.
Closed!
INFO:pleaseopme:Auto mode #chan 포도 v

The problem here is that the bot tries to +v the user 포도 indefinitely.
When another user B enters the channel, the bot will not process the new user B.

**Comment by chfoo** [comment]
@forcecore: I pushed a fix for the op & voice issue. But I can't replicate your other issue yet because I can't configure my IRC server to accept international nicknames.

**Comment by forcecore** [comment]
I tested the new version in a private channel and real channel and the +op was successful for both channels. Things worked fine for international nicknames too!

**Comment by rwoodpecker** [comment]
Closing as appears to be resolved.
